// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaapedxgvyucrhppeeiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhYXBlZHhndnl1Y3JocHBlZWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODU3MDUsImV4cCI6MjA2NTY2MTcwNX0.h0oegy0flsAUiKtb167jopb9Jk1bN8XFckw0-Ykf6Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);